baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kuwait Azure Community'
theme = 'hugo-simple'
buildFuture = true

[params]
favicon = 'favicon.ico'
dateFormat = '2006-01-02'
hideRSSLink = true
hideMadeWithLine = true

[params.author]
name = 'Mohammad Asad Alahmadi'
email = 'mmohammadq8@outlook.com'

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10